image: node:18

stages:
  - test
  - deploy
  - pages

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  WDIO_CACHE_FOLDER: "$CI_PROJECT_DIR/.cache/WebdriverIO"
  REPORT_DIR: "wdio/reports"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - .cache/WebdriverIO
    - node_modules/

test:
  stage: test
  script:
    - npm config set -- '//gitlab.logio.cz/api/v4/packages/npm/:_authToken' "$CI_JOB_TOKEN"
    - npm ci --cache .npm --prefer-offline
    - npm run test:ci
    - npx mochawesome-merge "$REPORT_DIR"/*.json -o "$REPORT_DIR"/merged-report.json
    - npx mochawesome-report-generator "$REPORT_DIR"/merged-report.json -o "$CI_PROJECT_DIR/wdio/mochawesome-html-report" --reportTitle "Test Report"
  artifacts:
    when: always
    paths:
      - wdio/reports/**/*.json
      - wdio/reports/merged-report.json
      - wdio/mochawesome-html-report/*.html
    expire_in: 1 week

pages:
  image: node:latest
  stage: deploy
  dependencies:
    - test
  script:
    - mkdir -p public
    - npx marge "$REPORT_DIR"/merged-report.json --reportDir public --reportTitle "Test Report"
  when: always
  only:
    - master
  artifacts:
    paths:
      - public
    expire_in: 30 days
